import Head from "next/head";
import Link from "next/link";
import GitHubStars from "../components/GithubStars";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="nav shadow-md shadow-gray-400">
        <div className="nav-item">
          <Link href="/">IE</Link>
        </div>
      </div>
      <main className="flex flex-col items-center justify-center w-full px-20 text-center">
        <GitHubStars />
      </main>
    </>
  );
}
